Repository hed-standard/hed-javascript, pull requests merged in 2024-10, with the labels that each got.

#197 Add isError method to Issue class
  common/issues/issues.js
Labels: enhancement, quality

#199 Convert Memoizer back to plain class
  utils/types.js
Labels: quality

#201 Move all throws of IssueError to new static method
  bids/schema.js
  bids/types/json.js
  bids/types/tsv.js
  bids/validator/bidsHedSidecarValidator.js
  common/issues/issues.js
  common/schema/loader.js
  parser/converter.js
  parser/parsedHedGroup.js
  utils/types.js
  validator/schema/hed3.js
Labels: quality

#200 Throw errors from ParsedHedTag constructors instead of using field
  parser/parsedHedTag.js
  parser/splitHedString.js
  tests/bids.spec.js
  tests/dataset.spec.js
  tests/stringParser.spec.js
  utils/hedData.js
  validator/hed2/parser/parsedHed2Tag.js
Labels: quality, tests, hed 3, parsing

#202 Move HED 3 requireChild testing to TagConverter and refactor that class
  parser/converter.js
  parser/parsedHedGroup.js
  parser/parsedHedTag.js
  tests/event.spec.js
  validator/event/hed3.js
  validator/event/validator.js
  validator/hed2/event/hed2Validator.js
Labels: quality, tests, hed 3, validation, conversion, parsing

#207 Added develop branch to github ci action
  .github/workflows/ci.yml
Labels: repo-management
