Repository hed-standard/hed-javascript, pull requests merged in 2025-08, with the labels that each got.

#515 Updated the main package configuration for jest
  README.md
  babel.config.cjs
  fileTransformer.js
  jest.config.js
  package-lock.json
  package.json
Labels: tests, repo-management

#525 Replace CRLF line breaks with LF
  browser/jest.config.cjs
  browser/src/schema/init.js
  browser/src/schema/loader.spec.js
  browser/src/schema/vite-importer.js
  browser/vite-importer-transformer.cjs
  browser/vitest.config.js
  jest.config.js
Labels: quality

#529 Install current version of npm in publish script
  .github/workflows/publish.yml
Labels: repo-management

#530 Switch from cross-fetch to internal Node version
  browser/jest.config.cjs
  browser/package-lock.json
  browser/package.json
  esbuild.mjs
  jest.config.js
  package-lock.json
  package.json
  src/utils/files.js
Labels: bug, dependencies, tests, repo-management, web, utils

#531 Updated test configuration to be compatible with node 22
  babel.config.js
  browser/package-lock.json
  jest.config.js
  package-lock.json
  package.json
  src/utils/files.js
Labels: dependencies, tests, repo-management

#534 Updated all actions to use node versions >= 22.x
  .github/workflows/deploy-pages.yml
  .github/workflows/test-types.yml
  .github/workflows/tests.yml
Labels: dependencies, tests, repo-management

#537 Merge ESM builds
  esbuild.mjs
  package.json
  scripts/test-types-local-unix.sh
  scripts/test-types-local.js
Labels: repo-management

#538 Release version 4.1.4
  package-lock.json
  package.json
Labels: repo-management
